# Run this to create: conda env create --force -f environment.yml
name: tulsa_summary
channels:
    - conda-forge
dependencies:
    - python=3.6
    - astropy
    - datashader
    - jupyterlab
    - numpy
    - scikit-learn
    - scipy
    - statsmodels
    - sympy
    - matplotlib

    - pip:
        - altair
        - braket-daq
        - cython
        - easier
        - gspread
        - holoviews[all]
        - oauth2client
        - pandashells[full]
        - pdvega
        - pymc3
        - flake8
        - mypy


